# Generated by Django 2.2 on 2019-04-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_logincredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
