# Generated by Django 2.2 on 2019-04-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20190422_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
